# Generated by Django 4.1.7 on 2023-03-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connect", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectmeuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="connectmeuser",
            name="deleted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="connectmeuser",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
