# Generated by Django 4.1.7 on 2023-03-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connect", "0002_alter_connectmeuser_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectmeuser",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="connectmeuser",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
