# Generated by Django 4.1.7 on 2023-04-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connect", "0003_alter_connectmeuser_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectmeuser",
            name="access_token",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="connectmeuser",
            name="access_token_validity",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectmeuser",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="connectmeuser",
            name="refresh_token_validity",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
