# Generated by Django 4.1.7 on 2023-04-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connect", "0004_connectmeuser_access_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectmeuser",
            name="access_token_validity",
        ),
        migrations.RemoveField(
            model_name="connectmeuser",
            name="refresh_token_validity",
        ),
        migrations.AlterField(
            model_name="connectmeuser",
            name="access_token",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="connectmeuser",
            name="refresh_token",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
